{
 "title": "CPU utilization (в процентах, 100 - idle)",
 "description": "Панель утилизация CPU для nodeexporter (в процентах, 100-idle);",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HDD занятое место от 0 до 100%",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (\n  node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay\", mountpoint=\"/\"} \n  / \n  node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\", mountpoint=\"/\"}\n)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utilization (в процентах, 100 - idle)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "description": "Панель загрузки Load Average (1 / 5 / 15)",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 22 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" },
    { "expr": "node_load5", "legendFormat": "__auto" },
    { "expr": "node_load15", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAM Оперативная память",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}